export default COLOR = {
    PRIMARY:'#2D0569',
    PRIMARYTRANSPARENCY :(opacity = 0.5) => (`rgba(45,5,105,${opacity})`),
    FONTGREY: '#9DA1AD',
    FONTBLACK: '#000000',
    FONTLIGHT: '#EFF0F2',
    WHITE:'#FFFF',
    GRADIENTLEFT:'#F6AC2C',
    GRADIENTCENTER:'#F6AC2C',
    GRADIENTRIGHT:'#F18A3F'
}